:backgroundrb: 
  :port: 11006
  :ip: 0.0.0.0
:schedules:
  :report_worker:
    :delete_temporary_reports:
      :trigger_args:
        :start: <%= Time.now + 5.seconds %>
        :end: <%= Time.now + 10.minutes %>
        :repeat_interval: <%= 10.seconds %>