development:
  morphology: none
  min_word_len: 4
  min_prefix_len: 4
  enable_star: 1
  port: 4000

test:
  morphology: none
  min_word_len: 4
  min_prefix_len: 4
  enable_star: 1
  port: 4001

selenium:
  morphology: none
  min_word_len: 4
  min_prefix_len: 4
  enable_star: 1
  port: 4002

production:
  morphology: none
  min_word_len: 4
  min_prefix_len: 4
  enable_star: 1
  port: 4003