<% require 'socket' %>
<% machine_name = Socket.gethostname %>

development:
  min_prefix_len: 3
  enable_star: 1
  port: 3312

test:
  min_prefix_len: 3
  enable_star: 1
<% case machine_name; when "stallman.rootnode.net" then %>
  port: 3041
<% else %>
  port: 11214
<% end %>

selenium:
  min_prefix_len: 3
  enable_star: 1
  port: 11213

production:
  min_prefix_len: 3
  enable_star: 1
  port: 3042